system = require('system')
fs = require('fs')
page = require("webpage").create()

page.onConsoleMessage = (msg, line, source) ->
  console.log "console> " + msg # + " @ line: " + line

if system.args.length < 5
  console.error "This program takes exactly 4 arguments:"
  console.error "CSS/LESS file (for example '/home/my-home/style.css)"
  console.error "Absolute path to html file (for example '/home/my-home/file.xhtml)"
  console.error "Output (X)HTML file"
  console.error "Output CSS file"
  console.error "Additional config params passed to the EpubCSS constructor:"
  console.error "  debug=true"
  console.error "  autogenerateClasses=false"
  # console.error "  bakeInAllStyles=true"
  phantom.exit 1

cssFile = system.args[1]
address = system.args[2]

# Verify address is an absolute path
# TODO: convert relative paths to absolute ones
if address[0] != '/'
  console.error "Path to HTML file does not seem to be an absolute path. For now it needs to start with a '/'"
  phantom.exit 1
address = "file://#{address}"

outputFile = fs.open(system.args[3], 'w')

SPECIAL_CSS_FILE_NAME = '__AUTOGENERATED_CSS_FILE'
outputCSSFile = fs.open(system.args[4], 'w')

config = {}
if system.args.length > 5
  for param in system.args.slice(5)
    [name, value] = param.split('=')
    val = value == 'true'
    config[name] = val

# Alert dumps to the current file
currentFile = { file: outputFile, name: 'Output HTML' }
lines = 0
page.onAlert = (msg) ->
  if lines++ % 100000 == 0
    console.log "Outputting #{currentFile.name} ..."
    lines = lines % 100000
  currentFile.file.write msg


# Confirm changes the name of the file
page.onConfirm = (fileName) ->
  currentFile.file.close()
  if fileName == SPECIAL_CSS_FILE_NAME
    currentFile.file = outputCSSFile
    currentFile.name = "Autogenerated CSS file"
  currentFile.file = fs.open('tempdir/' + fileName, 'w')
  currentFile.name = fileName
  lines = 0
  true

console.log "Reading CSS file at: #{cssFile}"
lessFile = fs.read(cssFile, 'utf-8')

console.log "Opening page at: #{address}"
startTime = new Date().getTime()




page.open encodeURI(address), (status) ->
  if status != 'success'
    console.error "File not FOUND!!"
    phantom.exit(1)

  console.log "Loaded? #{status}. Took #{((new Date().getTime()) - startTime) / 1000}s"
  
  loadScript = (path) ->
    if page.injectJs(path)
    else
      console.error "Could not find #{path}"
      phantom.exit(1)
  
  loadScript(fs.workingDirectory + '/lib/jquery.js')
  loadScript(fs.workingDirectory + '/lib/less-1.3.0.js')
  loadScript(fs.workingDirectory + '/custom.js')
  loadScript(fs.workingDirectory + '/epubcss.js')
  loadScript(fs.workingDirectory + '/lib/dom-to-xhtml.js')

  num = page.evaluate((lessFile, config, SPECIAL_CSS_FILE_NAME) ->
  
    parser = new (window.EpubCSS)(config)
    { css:newCSS, files:files } = parser.emulate(lessFile)

    # Hack to serialize out the HTML (sent to the console)
    console.log 'Serializing (X)HTML back out from WebKit...'
    aryHack =
      push: (str) -> alert str
    
    alert '<html xmlns="http://www.w3.org/1999/xhtml">'
    window.dom2xhtml.serialize($('body')[0], aryHack)
    alert '</html>'
    
    confirm(SPECIAL_CSS_FILE_NAME)
    alert(newCSS)
    
    for name, $nodes of files
      confirm name
      alert '<html xmlns="http://www.w3.org/1999/xhtml">'
      alert '<head><link rel="stylesheet" href="style.css"/></head>'
      $nodes.each () ->
        window.dom2xhtml.serialize($(@)[0], aryHack)
      alert '</html>'
        

  , lessFile, config, SPECIAL_CSS_FILE_NAME)
  currentFile.file.close()
  phantom.exit()
